MyFinance/MyFinance/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyFinance.DB;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class CategoryController : Controller
    {
        private MyFinanceDbContext _dbContext;

        public CategoryController(MyFinanceDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var categories = _dbContext.Categories.ToList();

            return View(categories);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Category category)
        {
            ModelState.Clear();

            if (!category.Validate(ModelState))
            {
                TempData["error"] = "Invalid input";

                return View(category);
            }
            else
            {
                _dbContext.Add(category);
                _dbContext.SaveChanges();

                TempData["success"] = "Successfully added";

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var category = _dbContext.Categories.FirstOrDefault(c => c.Id == id);

            return View(category);
        }

        [HttpPost]
        public IActionResult Update(Category category)
        {
            ModelState.Clear();

            if (!category.Validate(ModelState))
            {
                TempData["error"] = "Invalid input";

                return View(category);
            }
            else
            {
                _dbContext.Update(category);
                _dbContext.SaveChanges();

                TempData["success"] = "Successfully updated";

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var category = _dbContext.Categories.FirstOrDefault(c => c.Id == id);

            return View(category);
        }

        [HttpPost]
        public IActionResult Delete(Category category)
        {
            _dbContext.Remove(category);
            _dbContext.SaveChanges();

            TempData["success"] = "Successfully deleted";

            return RedirectToAction("Index");
        }
    }
}

MyFinance/MyFinance/Controllers/SpendingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyFinance.DB;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class SpendingController : Controller
    {
        private MyFinanceDbContext _dbContext;

        public SpendingController(MyFinanceDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var spendings = _dbContext.Spendings
                .Include(s => s.Category)
                .OrderBy(s => s.DateTime)
                .Reverse()
                .ToList();

            return View(spendings);
        }

        [HttpGet]
        public IActionResult Add()
        {
            SetCategories();

            return View();
        }

        [HttpPost]
        public IActionResult Add(Spending spending)
        {
            ModelState.Clear();

            if (!spending.Validate(ModelState))
            {
                SetCategories();
                TempData["error"] = "Invalid input";

                return View(spending);
            }
            else
            {
                _dbContext.Add(spending);
                _dbContext.SaveChanges();

                TempData["success"] = "Successfully added";

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            SetCategories();
            var spending = _dbContext.Spendings.Include(s => s.Category).FirstOrDefault(s => s.Id == id);

            return View(spending);
        }

        [HttpPost]
        public IActionResult Update(Spending spending)
        {
            ModelState.Clear();

            if (!spending.Validate(ModelState))
            {
                SetCategories();
                TempData["error"] = "Invalid input";

                return View(spending);
            }
            else
            {
                _dbContext.Update(spending);
                _dbContext.SaveChanges();

                TempData["success"] = "Successfully updated";

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var spending = _dbContext.Spendings.Include(s => s.Category).FirstOrDefault(s => s.Id == id);

            return View(spending);
        }

        [HttpPost]
        public IActionResult Delete(Spending spending)
        {
            _dbContext.Remove(spending);
            _dbContext.SaveChanges();

            TempData["success"] = "Successfully deleted";
            
            return RedirectToAction("Index");
        }

        private void SetCategories()
        {
            var categories = _dbContext.Categories.ToList();

            List<SelectListItem> cat = categories
                .Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();

            ViewData["Categories"] = cat;
        }
    }
}

MyFinance/MyFinance/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyFinance.DB;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class StatisticsController : Controller
    {
        private MyFinanceDbContext _dbContext;

        public StatisticsController(MyFinanceDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            SetDates();
            var statistics = new Statistics(DateTime.Now.Month, DateTime.Now.Year);

            return View(statistics);
        }

        [HttpPost]
        public IActionResult Index(Statistics statistics)
        {
            ModelState.Clear();
            SetDates();

            statistics.Spendings = _dbContext.Spendings
                .Include(s => s.Category)
                .Where(s => s.DateTime.Month == statistics.Month && s.DateTime.Year == statistics.Year)
                .Select(s => s)
                .OrderBy(s => s.DateTime)
                .Reverse()
                .ToList();

            return View(statistics);
        }

        private void SetDates()
        {
            SetMonths();
            SetYears();
        }
        private void SetMonths()
        {
            List<SelectListItem> months = Enumerable.Range(1, 12)
                .Select(m => new SelectListItem
                {
                    Value = m.ToString(),
                    Text = m.ToString()
                }).ToList();

            ViewData["Months"] = months;
        }
        private void SetYears()
        {
            var date = DateTime.Now.Year - 10;

            List<SelectListItem> years = Enumerable.Range(date, DateTime.Now.Year - date + 1)
                .Select(y => new SelectListItem
                {
                    Value = y.ToString(),
                    Text = y.ToString()
                }).ToList();

            ViewData["Years"] = years;
        }
    }
}

MyFinance/MyFinance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFinance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFinance.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-safe2"></i>&nbsp;&nbsp;MyFinance</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Spending" asp-action="Index">Spendings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Statistics" asp-action="Index">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyFinance - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>